name: 'Setup Msys2 environment'
description: 'Setup an Msys2 environment and provide an msys2do helper'
author: 'NumWorks'
inputs:
  msystem:
    description: 'Variant of the environment to set by default: MSYS, MINGW32 or MINGW64'
    required: false
    default: 'MINGW64'
runs:
  using: 'node12'
  main: 'index.js'
