name: 'action'
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3,6'
jobs:

  powershell:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build action
      shell: bash
      run: |
        npm ci
        npm run build
        rm -rf node_modules
    - name: run action
      uses: ./
    - name: test MSYS
      run: |
        $env:MSYSTEM = 'MSYS'
        msys2do ./test.sh MSYS
    - name: test MINGW64
      run: |
        $env:MSYSTEM = 'MINGW64'
        msys2do ./test.sh MINGW64
    - name: test MINGW32
      run: |
        $env:MSYSTEM = 'MINGW32'
        msys2do ./test.sh MINGW32

  cmd:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build action
      shell: bash
      run: |
        npm ci
        npm run build
        rm -rf node_modules
    - name: run action
      uses: ./
    - name: test MSYS
      shell: cmd
      run: |
        set MSYSTEM=MSYS
        msys2do ./test.sh MSYS
    - name: test MINGW64
      shell: cmd
      run: |
        set MSYSTEM=MINGW64
        msys2do ./test.sh MINGW64
    - name: test MINGW32
      shell: cmd
      run: |
        set MSYSTEM=MINGW32
        msys2do ./test.sh MINGW32

  env:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build action
      shell: bash
      run: |
        npm ci
        npm run build
        rm -rf node_modules
    - name: run action
      uses: ./
    - name: test MSYS
      run: msys2do ./test.sh MSYS
      env:
        MSYSTEM: MSYS
    - name: test MINGW64
      run: msys2do ./test.sh MINGW64
      env:
        MSYSTEM: MINGW64
    - name: test MINGW32
      run: msys2do ./test.sh MINGW32
      env:
        MSYSTEM: MINGW32

  msystem:
    strategy:
      matrix:
        task: [ MSYS, MINGW64, MINGW32 ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build action
      shell: bash
      run: |
        npm ci
        npm run build
        rm -rf node_modules
    - name: run action
      uses: ./
      with:
        msystem: ${{ matrix.task }}
    - run: msys2do ./test.sh ${{ matrix.task }}

  update:
    strategy:
      matrix:
        task: [ MSYS, MINGW64, MINGW32 ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build action
      shell: bash
      run: |
        npm ci
        npm run build
        rm -rf node_modules
    - name: run action
      uses: ./
      with:
        update: True
        msystem: ${{ matrix.task }}
    - run: msys2do ./test.sh ${{ matrix.task }}

  MSYS2_PATH_TYPE:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-go@v1
    - uses: actions/checkout@v1
    - name: build action
      shell: bash
      run: |
        npm ci
        npm run build
        rm -rf node_modules
    - name: run action
      uses: ./
    - run: msys2do go env
      env:
        MSYS2_PATH_TYPE: inherit

  path-type:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-go@v1
    - uses: actions/checkout@v1
    - name: build action
      shell: bash
      run: |
        npm ci
        npm run build
        rm -rf node_modules
    - name: run action
      uses: ./
      with:
        path-type: inherit
    - run: msys2do go env
